/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface-container-lowest": "#0a0e16",
          "inverse-primary": "#006875",
          "tertiary-container": "#ffc3a7",
          "secondary": "#b0c6ff",
          "surface-variant": "#31353e",
          "tertiary-fixed-dim": "#ffb692",
          "on-error-container": "#ffdad6",
          "outline-variant": "#3b494c",
          "on-primary-container": "#00626e",
          "on-secondary-fixed": "#001945",
          "error": "#ffb4ab",
          "error-container": "#93000a",
          "on-secondary-container": "#f2f3ff",
          "surface-tint": "#00daf3",
          "tertiary-fixed": "#ffdbcb",
          "tertiary": "#ffe8de",
          "secondary-fixed": "#d9e2ff",
          "on-primary-fixed": "#001f24",
          "on-surface-variant": "#bac9cc",
          "surface-container-high": "#262a33",
          "surface-container-highest": "#31353e",
          "on-surface": "#e0e2ee",
          "on-tertiary-fixed": "#341100",
          "primary": "#c3f5ff",
          "surface": "#10131c",
          "primary-fixed-dim": "#00daf3",
          "on-tertiary": "#562000",
          "inverse-surface": "#e0e2ee",
          "secondary-fixed-dim": "#b0c6ff",
          "on-background": "#e0e2ee",
          "surface-container": "#1c2028",
          "surface-container-low": "#181c24",
          "on-secondary": "#002d6e",
          "secondary-container": "#0068ed",
          "on-tertiary-container": "#963d00",
          "on-tertiary-fixed-variant": "#7a3000",
          "inverse-on-surface": "#2d303a",
          "surface-dim": "#10131c",
          "on-primary": "#00363d",
          "primary-fixed": "#9cf0ff",
          "on-primary-fixed-variant": "#004f58",
          "outline": "#849396",
          "primary-container": "#00e5ff",
          "on-error": "#690005",
          "on-secondary-fixed-variant": "#00429b",
          "surface-bright": "#353943",
          "background": "#10131c"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "unit": "4px",
          "stack-md": "12px",
          "stack-lg": "24px",
          "gutter": "1rem",
          "density-normal": "0.75rem",
          "density-compact": "0.25rem",
          "stack-sm": "4px",
          "container-padding": "1.5rem"
      },
      "fontFamily": {
          "headline-md": ["JetBrains Mono"],
          "body-lg": ["Inter"],
          "metric-xl": ["JetBrains Mono"],
          "label-xs": ["JetBrains Mono"],
          "label-md": ["JetBrains Mono"],
          "body-md": ["Inter"],
          "body-sm": ["Inter"],
          "metric-lg": ["JetBrains Mono"]
      },
      "fontSize": {
          "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
          "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "metric-xl": ["40px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "label-xs": ["10px", { "lineHeight": "12px", "letterSpacing": "0.05em", "fontWeight": "700" }],
          "label-md": ["13px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
          "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
          "body-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
          "metric-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
